### ISSUE TITLE
empty uid

### ISSUE THREAD

**Issue by ardeus-ua** [srozb/HomeAssistant-GreeClimateComponent#1]
Home Assistant 0.92b3 gives error on startup:

`ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 363, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 548, in async_added_to_hass
    self.SyncState()
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 326, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 223, in GreeGetValues
    jsonPayloadToSend = '{"cid":"app","i":0,"pack":"' + base64.b64encode(self.CIPHER.encrypt(self.Pad('{"cols":' + simplejson.dumps(propertyNames) + ',"mac":"' + str(self._mac_addr) + '","t":"status"}').encode("utf8"))).decode('utf-8') + '","t":"pack","tcid":"' + str(self._mac_addr) + '","uid":{}'.format(self._uid) + '}'
AttributeError: 'GreeClimate' object has no attribute '_uid'`

**Comment by srozb** [comment]
Can you paste your climate.yaml values?

**Comment by ardeus-ua** [comment]
- platform: gree
    name: 'Livingroom AC'
    host: '192.168.1.48'
    port: 7000
    mac: 'F4:91:1E:31:9E:D5' # (AC_MAC)
    encryption_key: 'l0No3Qr6Tu9Wx2Za'
    min_temp: 16
    max_temp: 30
    target_temp: 20
    temp_sensor: sensor.livingroom_temperature
    uid: 0
  - platform: gree
    port: 7000
    name: 'Bedroom AC'
    host: '192.168.1.49'
    mac: 'F4911E319F58' # (AC_MAC)
    encryption_key: 'o3Qr6Tu9Wx2Za5Cd'
    min_temp: 16
    max_temp: 30
    target_temp: 20
    temp_sensor: sensor.bedroom_temperature
    uid: 0

I have tried both with and without uid

**Comment by srozb** [comment]
Take a look at your `mac` parameter. I'd change `F4911E319F58` to `F4:91:1E:31:9F:58`. I'd also try stable version of HA (0.92) as it's been already released.

**Comment by ardeus-ua** [comment]
Hello @srozb, I have kept : on purpose since it works no matter if there is colon or not. Checked with 0.92 and got the same result

**Comment by ardeus-ua** [comment]
Hello @srozb, my log wasn't full, actually. I have 2 devices and they give errors on HA restart and while fetching the state of the A/C

2019-04-29 15:23:47 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 363, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 548, in async_added_to_hass
    self.SyncState()
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 326, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 223, in GreeGetValues
    jsonPayloadToSend = '{"cid":"app","i":0,"pack":"' + base64.b64encode(self.CIPHER.encrypt(self.Pad('{"cols":' + simplejson.dumps(propertyNames) + ',"mac":"' + str(self._mac_addr) + '","t":"status"}').encode("utf8"))).decode('utf-8') + '","t":"pack","tcid":"' + str(self._mac_addr) + '","uid":{}'.format(self._uid) + '}'
AttributeError: 'GreeClimate' object has no attribute '_uid'
2019-04-29 15:24:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.livingroom_ac fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 408, in update
    self.SyncState()
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 326, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 223, in GreeGetValues
    jsonPayloadToSend = '{"cid":"app","i":0,"pack":"' + base64.b64encode(self.CIPHER.encrypt(self.Pad('{"cols":' + simplejson.dumps(propertyNames) + ',"mac":"' + str(self._mac_addr) + '","t":"status"}').encode("utf8"))).decode('utf-8') + '","t":"pack","tcid":"' + str(self._mac_addr) + '","uid":{}'.format(self._uid) + '}'
AttributeError: 'GreeClimate' object has no attribute '_uid'

**Comment by srozb** [comment]
@ardeus-ua try to change `uid=None` to `uid=0` in 120 line of `climate.py`:

```
    def __init__(self, hass, name, ip_addr, port, mac_addr, min_temp, max_temp, target_temp, target_temp_step, temp_sensor_entity_id, operation_list, fan_list, swing_updn_mode_list, default_operation, default_fan_mode, default_operation_from_idle, default_swing_updn_mode, encryption_key=None, uid=None):
```

to:
```
    def __init__(self, hass, name, ip_addr, port, mac_addr, min_temp, max_temp, target_temp, target_temp_step, temp_sensor_entity_id, operation_list, fan_list, swing_updn_mode_list, default_operation, default_fan_mode, default_operation_from_idle, default_swing_updn_mode, encryption_key=None, uid=0):
```

and let me know if that helped

**Comment by ardeus-ua** [comment]
@srozb, same errors in log

**Comment by srozb** [comment]
use `climate.py` from branch `fix set_uid`: https://github.com/srozb/HomeAssistant-GreeClimateComponent/blob/uid_fix/custom_components/gree/climate.py

**Comment by ardeus-ua** [comment]
Thank you, @srozb, it worked. No more errors are thrown into log

**Comment by srozb** [comment]
cool, @ardeus-ua what is your hvac model by the way?

**Comment by ardeus-ua** [comment]
Cooper Hunter CH-S09FTXQ Veritas Inverter with WiFi

**Comment by srozb** [comment]
Consider to switch to [the original repo](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent) maintained by Rob. It should work for you and this repo might be unmaintained soon.
